### ISSUE TITLE
code for downloading torrents

### ISSUE THREAD

**Issue by bitterypaul** [bbougot/Yak#1]
please tell me where the code for downloading torrents are. where is dllimport to make use of libtorrent. Is libtorrent.dll  named as torrent.dll

**Comment by bbougot** [comment]
The downloading part relies on Ragnar (the libtorrent-rasterbar wrapper). 
The entry point is in the MainViewModel class, in the DownloadMovie method. As soon as we add a torrent in the using(Session...) part (l.712), the download starts. Ragnar is added in the project via NuGet, which also also adds the libtorrent libraries (including libtorrent.dll and 4 C++ boost libraries). All of them are used by the Ragnar dependency located in the package NuGet folder whose the reference is added in the Yak project.
