### ISSUE TITLE
I cannot build the sln

### ISSUE THREAD

**Issue by tidusjar** [bbougot/Yak#2]
Hello,

I would like to start contributing to your project but I cannot build the solution.
I am getting the error: 
Severity	Code	Description	Project	File	Line
Error		Ce projet fait référence à des packages NuGet qui sont manquants sur cet ordinateur. Activez l'option de restauration des packages NuGet pour les télécharger. Pour plus d'informations, consultez http://go.microsoft.com/fwlink/?LinkID=322105. Le fichier manquant est le suivant : C:\Users\Jamie\Source\Repos\Yak\\.nuget\NuGet.targets.	Yak	C:\Users\Jamie\Source\Repos\Yak\Yak\Yak.csproj	1310

I have enabled Auto package restore but it is not working. I forked the solution and it contains a .nuget folder with some files in there, but this does not exist. The .sln still thinks it does exist.

**Comment by bbougot** [comment]
Hi,

I've added the missing .nuget folder. Please update and click "Restore" in the Package Manager Console tab under Visual Studio.

**Comment by tidusjar** [comment]
This has now been fixed :)
